#!/bin/bash

./system_backup.sh

cp ./usr/mhs35-overlay.dtb /boot/overlays/
cp ./usr/mhs35-overlay.dtb /boot/overlays/mhs35.dtbo
cp boot/cmdline.*.txt boot/config.*.txt /boot/


# Inject cmdline.txt
if [ ! -s /boot/cmdline.txt ]; then
    echo "Error: /boot/cmdline.txt not found, please mount your /boot folder!"
    exit 1
fi
for opt in "fbcon=map:10" "fbcon=font:ProFont6x11" "logo.nologo"; do
	if [ `grep "$opt" /boot/cmdline.txt | wc -c` != 0 ]; then
		continue
	fi
	echo -n " $opt" >>/boot/cmdline.txt
done


# Inject config.txt
if [ ! -s /boot/config.txt ]; then
    echo "Error: /boot/config.txt not found, please mount your /boot folder!"
    exit 1
fi
for config in "hdmi_force_hotplug=1" "dtparam=i2c_arm=on" "dtparam=spi=on" "enable_uart=1" "dtoverlay=mhs35:rotate=90" \
	"hdmi_group=2" "hdmi_mode=85" "hdmi_drive=2"; do
	if [ `grep "^$config" /boot/config.txt | wc -l` != 0 ]; then
		continue
	fi
	if [ `grep "^#\+$config" /boot/config.txt | wc -l` != 0 ]; then
		sed -i "s/^#\+$config/$config/g" /boot/config.txt
	fi
done
if [ `grep "^dtoverlay=vc4-kms-v3d" /boot/config.txt | wc -c` != 0 ]; then
	sed -i "s:^dtoverlay=vc4-kms-v3d:dtoverlay=vc4-fkms-v3d:g" /boot/config.txt
elif [ `grep "^#dtoverlay=vc4-kms-v3d" /boot/config.txt | wc -c` != 0 ]; then
	sed -i "s:^#dtoverlay=vc4-kms-v3d:dtoverlay=vc4-kms-v3d:g" /boot/config.txt
else
	echo "dtoverlay=vc4-kms-v3d" >>/boot/config.txt
fi


rm -rf /etc/X11/xorg.conf.d/40-libinput.conf
mkdir -p /etc/X11/xorg.conf.d
cp -rf ./usr/99-calibration.conf-mhs35-90  /etc/X11/xorg.conf.d/99-calibration.conf
cp -rf ./usr/99-fbturbo.conf  /usr/share/X11/xorg.conf.d/99-fbturbo.conf

cp ./usr/inittab /etc/
touch ./.have_installed
echo "gpio:resistance:mhs35:90:480:320" > ./.have_installed

#FBCP install
wget --spider -q -o /dev/null --tries=1 -T 10 https://github.com
if [ $? -eq 0 ]; then
	cp -rf ./usr/99-fbturbo-fbcp.conf  /usr/share/X11/xorg.conf.d/99-fbturbo.conf
	apt-get install git cmake -y 2> error_output.txt
	result=`cat ./error_output.txt`
	echo -e "\033[31m$result\033[0m"
	grep -q "^E:" ./error_output.txt && exit
	rm -rf rpi-fbcp
	git clone https://github.com/tasanakorn/rpi-fbcp
	mkdir ./rpi-fbcp/build
	cd ./rpi-fbcp/build/
	cmake ..
	make
	install fbcp /usr/local/bin/fbcp
	if [ ! "`grep '^[^#].*fbcp' /etc/rc.local`" ]; then
		sed -i "/^exit 0/d" /etc/rc.local
		echo 'sleep 7; fbcp &' >>/etc/rc.local
		echo 'exit 0' >>/etc/rc.local
	fi
	cd - > /dev/null
fi
#evdev install
#nodeplatform=`uname -n`
#kernel=`uname -r`
version=`uname -v`
#if test "$nodeplatform" = "raspberrypi";then
#echo "this is raspberrypi kernel"
version=${version##* }
#version=${version#*#}
echo $version
if test $version -lt 2017;then
	echo "reboot"
else
	echo "need to update touch configuration"
	apt-get install xserver-xorg-input-evdev  2> error_output.txt
	result=`cat ./error_output.txt`
	echo -e "\033[31m$result\033[0m"
	grep -q "error:" ./error_output.txt && exit
	cp -rf /usr/share/X11/xorg.conf.d/10-evdev.conf /usr/share/X11/xorg.conf.d/45-evdev.conf
#echo "reboot"
fi
#else
#echo "this is not raspberrypi kernel, no need to update touch configure, reboot"
#fi

sync
sync
sleep 1
if [ $# -eq 1 ]; then
./rotate.sh $1
elif [ $# -gt 1 ]; then
echo "Too many parameters"
fi

echo "reboot now"
reboot
